package.path = vim.env.DOTFILES_TEST_ROOT .. "/tests/neovim/?.lua;" .. package.path
local control = require("fixtures.agency_control")
describe("Agency ACP roster lifecycle", function()
    local f
    before_each(function() f = require("fixtures.agency_native").new() end)
    after_each(function() f.close() end)
    it("removes timed out requests and ignores late replies", function()
        local calls, failure = 0, nil
        local request = require("sodium.agency.roster").new({ timeout_ms = 10 })
        request({ limit = 100 }, function(err) calls = calls + 1; failure = err end)
        f.flush()
        local frame = f.request("agency/roster")
        assert.are.equal("UNAVAILABLE", failure.code)
        assert.is_nil(f.client.callbacks[frame.id])
        f.client:_handle_message({ id = frame.id, result = {} })
        f.flush()
        assert.are.equal(1, calls)
    end)
    it("removes timed out readiness listeners without creating a new client", function()
        f.client.state = "initializing"
        local calls = 0
        local request = require("sodium.agency.roster").new({ timeout_ms = 10 })
        request({ limit = 100 }, function(err) assert.are.equal("UNAVAILABLE", err.code); calls = calls + 1 end)
        assert.are.equal(1, #f.client.ready_listeners)
        f.flush()
        assert.are.equal(0, #f.client.ready_listeners)
        assert.are.equal(1, calls)
    end)
    it("rejects malformed pages and reports missing methods without CLI fallback", function()
        local request = require("sodium.agency.roster").new()
        local failure
        for _, reply in ipairs({ {}, { handlerGeneration = control.id(2), state = "page", revision = control.id(500), agents = {}, issues = {}, nextCursor = "!" } }) do
            request({ limit = 100 }, function(err) failure = err end); f.flush()
            f.client:_handle_message({ id = f.request("agency/roster").id, result = reply }); f.flush()
            assert.are.equal("INVALID_PROTOCOL", failure.code)
        end
        request({ limit = 100 }, function(err) failure = err end); f.flush()
        f.client:_handle_message({ id = f.request("agency/roster").id, error = { code = -32601, message = "Method not found" } }); f.flush()
        assert.are.equal("UNAVAILABLE", failure.code)
        assert.is_truthy(failure.message:find("restart", 1, true))
    end)
    it("bounds complete traversal and settles exactly once after late pages", function()
        local callback, calls, failure, cancelled = nil, 0, nil, 0
        local operations = require("sodium.agency.operations").new({ roster_timeout_ms = 10,
            roster_request = function(_, cb) callback = cb; return function() cancelled = cancelled + 1 end end })
        operations.page({ active = true }, function(err) calls = calls + 1; failure = err end)
        f.flush()
        assert.are.equal("UNAVAILABLE", failure.code)
        assert.are.equal(1, cancelled)
        callback(nil, { handlerGeneration = control.id(2), result = control.page() })
        assert.are.equal(1, calls)
    end)
    it("rejects empty nonterminal pages", function()
        local failure
        local operations = require("sodium.agency.operations").new({ roster_request = function(_, cb)
            cb(nil, { handlerGeneration = control.id(2), result = control.page({}, "next") })
        end })
        operations.page({ active = true }, function(err) failure = err end)
        assert.are.equal("INVALID_PROTOCOL", failure.code)
    end)
    it("settles on connection loss and uses the same client after reconnection", function()
        local request = require("sodium.agency.roster").new()
        local calls, failure = 0, nil
        request({ limit = 100 }, function(err) calls = calls + 1; failure = err end); f.flush()
        f.client:_set_state("disconnected"); f.flush()
        assert.are.equal("UNAVAILABLE", failure.code)
        assert.are.equal(1, calls)
        f.client.state = "ready"
        request({ limit = 100 }, function(err) assert.is_nil(err); calls = calls + 1 end); f.flush()
        local page = control.page(); page.handlerGeneration = control.id(2)
        f.client:_handle_message({ id = f.request("agency/roster").id, result = page }); f.flush()
        assert.are.equal(2, calls)
    end)
end)