package.path = vim.env.DOTFILES_TEST_ROOT .. "/tests/neovim/?.lua;" .. package.path

describe("Agency view delivery and lifecycle", function()
    local f
    after_each(function()
        if f then
            f.close()
        end
        f = nil
    end)
    it("keeps annotations when submission acknowledgement is lost", function()
        f = require("fixtures.agency").view()
        f.add_annotation("review this line")
        f.submit()
        f.lose_reply()
        assert.are.equal(1, f.annotation_count())
        assert.are.equal("unknown", f.delivery_state())
        assert.are.equal(1, f.submit_count())
        f.submit()
        assert.are.equal(1, f.submit_count())
    end)
    it("clears only accepted captured revisions", function()
        f = require("fixtures.agency").view()
        f.add_annotation("original")
        f.set_draft("original draft")
        f.submit()
        f.add_annotation("later")
        f.set_draft("edited draft")
        f.acknowledge()
        f.acknowledge()
        assert.are.equal(1, f.annotation_count())
        assert.are.equal("edited draft", f.draft())
        assert.are.equal("accepted", f.delivery_state())
    end)
    it("does not optimistically duplicate the authoritative submitted event", function()
        f = require("fixtures.agency").view()
        f.set_draft("question")
        f.submit()
        assert.is_nil(f.transcript():find("question", 1, true))
        f.acknowledge()
        f.submitted_event()
        f.flush()
        local _, count = f.transcript():gsub("question", "")
        assert.are.equal(1, count)
    end)
    it("resolves a matching pending receipt from replay without resubmitting", function()
        f = require("fixtures.agency").view()
        f.add_annotation("captured")
        f.submit()
        f.lose_reply()
        f.reconnect_receipt()
        f.flush()
        assert.are.equal("accepted", f.delivery_state())
        assert.are.equal(0, f.annotation_count())
        assert.are.equal(1, f.submit_count())
    end)
    it("does not submit while the shared turn is running", function()
        f = require("fixtures.agency").view()
        f.busy()
        f.set_draft("question")
        f.submit()
        assert.are.equal(0, f.submit_count())
        assert.are.equal("question", f.draft())
    end)
    it("retains unknown delivery after a transport protocol failure", function()
        f = require("fixtures.agency").view()
        f.set_draft("question")
        f.submit()
        f.requests[1].callback({ code = "INVALID_PROTOCOL" })
        assert.are.equal("unknown", f.delivery_state())
        f.submit()
        assert.are.equal(1, f.submit_count())
    end)
    it("settles a submission callback only once", function()
        f = require("fixtures.agency").view()
        f.set_draft("question")
        local count = 0
        f.view.submit(function()
            count = count + 1
        end)
        f.acknowledge()
        f.acknowledge()
        assert.are.equal(1, count)
    end)
    it("does not downgrade authoritative acceptance when its reply is lost", function()
        f = require("fixtures.agency").view()
        f.add_annotation("captured")
        f.submit()
        f.submitted_event()
        f.lose_reply()
        assert.are.equal("accepted", f.delivery_state())
        assert.are.equal(0, f.annotation_count())
    end)
    it("disposes a closed tab view without invoking provider lifecycle", function()
        vim.cmd("tabnew")
        f = require("fixtures.agency").view()
        f.set_draft("unsent")
        vim.cmd("tabclose")
        vim.wait(50, function()
            return f.view.status().destroyed
        end)
        assert.is_true(f.view.status().destroyed)
        assert.are.equal(0, f.submit_count())
    end)
    it("invalidates queued renders when the view is hidden or wiped", function()
        f = require("fixtures.agency").view()
        f.set_draft("unsent")
        f.change()
        f.view.hide()
        f.flush()
        assert.are.equal(0, f.view.renderer.metrics().text_bytes)
        assert.are.equal("unsent", f.draft())
        f.view.show()
        local buf = f.view.widget.buf_nrs.chat
        f.change()
        vim.api.nvim_buf_delete(buf, { force = true })
        f.flush()
        assert.is_true(f.view.status().destroyed)
    end)
    it("does not rebuild when retention advances below the rendered suffix", function()
        f = require("fixtures.agency").view()
        f.snapshot.events = {}
        local fixture = require("fixtures.agency")
        for i = 1, 3000 do
            f.snapshot.events[i] = fixture.event(i, "x")
        end
        f.snapshot.lastSeq = 3000
        f.view.hide()
        f.view.show()
        local writer = f.view.renderer.writer
        f.snapshot.firstSeq = 100
        f.snapshot.historyTruncated = true
        f.change()
        f.flush()
        assert.are.equal(writer, f.view.renderer.writer)
    end)
    it("preserves changed context and draft after an explicit rejection", function()
        f = require("fixtures.agency").view()
        f.set_draft("question")
        f.view.add_context({
            buffer = 1,
            path = "/work/a/unsaved.lua",
            lines = { "first" },
            modified = true,
            file_type = "lua",
        })
        f.submit()
        f.requests[1].callback({ code = "NOT_READY", message = "busy" })
        assert.are.equal("rejected", f.delivery_state())
        assert.are.equal("question", f.draft())
        assert.are.equal(1, #f.view.code:get_selections())
    end)
    it("keeps hidden views empty on a continuously connected stream", function()
        f = require("fixtures.agency").retention({
            history_bytes = 65536,
            history_events = 128,
            text_bytes = 16384,
            lines = 200,
            tool_count = 8,
            tool_string_bytes = 8192,
        })
        f.show(1)
        f.show(2)
        f.hide(2)
        f.set_draft(1, "unsent")
        for i = 1, 1000 do
            f.tool(i, string.rep("x", 1024))
            f.flush()
            assert.is_true(f.projection().bytes <= 65536)
            assert.is_true(f.projection().events <= 128)
            assert.is_true(f.metrics(1).text_bytes <= 16384)
            assert.is_true(f.metrics(1).lines <= 200)
            assert.is_true(f.metrics(1).tool_count <= 8)
            assert.is_true(f.metrics(1).tool_string_bytes <= 8192)
            assert.are.equal(0, f.metrics(2).tool_count)
            assert.are.equal(0, f.metrics(2).text_bytes)
        end
        f.update_tool(1, "late update")
        f.flush()
        assert.is_true(f.has_partial_tool(1))
        f.show(2)
        assert.are.equal("unsent", f.draft(1))
        assert.are.equal(1, f.connections())
        assert.are.equal(0, f.replay_hook_calls())
    end)
    it("never constructs native lifecycle owners", function()
        local instance = require("agentic.acp.agent_instance")
        local chat = require("agentic.ui.chat_widget")
        local manager = require("agentic.session_manager")
        local get, new_chat, new_manager = instance.get_instance, chat.new, manager.new
        local function tripwire()
            error("native constructor invoked")
        end
        instance.get_instance, chat.new, manager.new = tripwire, tripwire, tripwire
        local ok, err = pcall(function()
            f = require("fixtures.agency").view()
            f.view.show()
            f.view.hide()
            f.view.show()
        end)
        instance.get_instance, chat.new, manager.new = get, new_chat, new_manager
        assert.is_true(ok, tostring(err))
    end)
end)