package.path = vim.env.DOTFILES_TEST_ROOT .. "/tests/neovim/?.lua;" .. package.path
local fixture = require("fixtures.agency_control")
describe("Agency native lifecycle operations", function()
    it("traverses every page and opens an exact live V3 target", function()
        local f = fixture.operations()
        local result
        f.operations.current("/work/a", function(err, manager) assert.is_nil(err); result = manager end)
        f.respond(1, fixture.page({}, "next"))
        f.respond(2, fixture.page({ fixture.agent(fixture.target_a) }))
        assert.are.equal("agency:" .. fixture.target_a.agentId, result.session_id)
        assert.are.equal(1, #f.opened)
    end)
    it("ensures an absent Handler once and checks its generation", function()
        local f = fixture.operations()
        local err
        f.operations.current("/work/a", function(error) err = error end)
        f.respond(1, nil, { code = "UNAVAILABLE" })
        f.respond(2, { phase = "ready" })
        f.respond(3, fixture.page(), nil, fixture.id(9))
        assert.are.equal("STALE_HANDLER", err.code)
        assert.are.equal(0, #f.opened)
    end)
    it("uses native backend-default creation when no active record exists", function()
        local f = fixture.operations()
        local result
        f.operations.current("/work/a", function(err, value) assert.is_nil(err); result = value end)
        f.respond(1, fixture.page())
        assert.are.equal("new", result)
        assert.are.equal(1, #f.calls)
    end)
    it("rejects inconsistent revisions, repeated cursors and unordered IDs", function()
        for _, mode in ipairs({ "revision", "cursor", "order" }) do
            local f = fixture.operations()
            local err
            f.operations.page({}, function(error) err = error end)
            f.respond(1, fixture.page({ fixture.agent(fixture.target_b) }, "next"))
            f.respond(2, fixture.page(mode == "order" and { fixture.agent(fixture.target_a) } or {},
                mode == "cursor" and "next" or nil, mode == "revision" and fixture.id(9) or nil))
            assert.are.equal("INVALID_PROTOCOL", err.code)
        end
    end)
    it("retries explicit inventory resynchronization only once", function()
        local f = fixture.operations()
        local err
        f.operations.page({}, function(error) err = error end)
        f.respond(1, nil, { code = "RESYNC_REQUIRED" })
        f.respond(2, nil, { code = "RESYNC_REQUIRED" })
        assert.are.equal("RESYNC_REQUIRED", err.code)
        assert.are.equal(2, #f.calls)
    end)
    it("does not create from partial inventory or imported non-live records", function()
        local f = fixture.operations()
        local err
        f.operations.current("/work/a", function(error) err = error end)
        local page = fixture.page()
        page.issues = { { message = "broken" } }
        f.respond(1, page)
        assert.are.equal("INCOMPLETE", err.code)
        local imported = fixture.agent(fixture.target_a, "stopped")
        imported.record.launch = vim.NIL
        f.operations.attach(fixture.target_a, function(error) err = error end)
        f.respond(2, fixture.page({ imported }))
        assert.are.equal("NOT_READY", err.code)
    end)
    it("pins stop to the exact observed tuple and does not retry uncertain mutations", function()
        local f = fixture.operations()
        local err
        f.operations.stop(fixture.target_a, function(error) err = error end)
        f.confirms[1].callback(true)
        assert.is_true(vim.tbl_contains(f.calls[1].argv, fixture.target_a.providerGeneration))
        f.respond(1, nil, { code = "UNAVAILABLE" })
        assert.are.equal("UNAVAILABLE", err.code)
        assert.are.equal(1, #f.calls)
        assert.is_not_nil(next(f.operations.pending()))
    end)
    it("rejects a successful receipt for a different target", function()
        local f = fixture.operations()
        local err
        f.operations.stop(fixture.target_a, function(error) err = error end)
        f.confirms[1].callback(true)
        f.respond(1, f.receipt(1, fixture.target_b, "stopped"))
        assert.are.equal("INVALID_PROTOCOL", err.code)
    end)
    it("reports a completed superseded restore without attaching or stopping it", function()
        local f = fixture.operations()
        local err
        f.operations.restore(fixture.target_a.agentId, function(error) err = error end)
        f.respond(1, { phase = "ready" })
        f.operations.detach()
        f.respond(2, f.receipt(2, fixture.target_a, "restored"))
        assert.are.equal("CANCELLED", err.code)
        assert.are.equal(1, #f.reports)
        assert.are.equal(0, #f.opened)
        assert.are.equal(2, #f.calls)
    end)
    it("verifies the restored tuple against inventory before opening", function()
        local f = fixture.operations()
        local result
        f.operations.restore(fixture.target_a.agentId, function(err, manager) assert.is_nil(err); result = manager end)
        f.respond(1, { phase = "ready" })
        f.respond(2, f.receipt(2, fixture.target_a, "restored"))
        f.respond(3, fixture.page({ fixture.agent(fixture.target_a) }))
        assert.are.equal("agency:" .. fixture.target_a.agentId, result.session_id)
    end)
end)