local utils = require("sodium.utils")

describe("sodium.utils", function()
    it("keeps Agency and native panels and other tabs out of editor discovery and closure", function()
        local editor = vim.api.nvim_get_current_win()
        vim.cmd.vsplit()
        local agency = vim.api.nvim_get_current_win()
        vim.w[agency].agency_bufnr = 123
        vim.cmd.vsplit()
        local native = vim.api.nvim_get_current_win()
        vim.w[native].agentic_bufnr = 124
        vim.cmd.tabnew()
        local other = vim.api.nvim_get_current_win()
        vim.cmd.tabprevious()
        assert.are.equal(editor, utils.editor_window())
        vim.api.nvim_set_current_win(editor)
        utils.close_non_agentic_windows()
        assert.is_true(vim.api.nvim_win_is_valid(agency))
        assert.is_true(vim.api.nvim_win_is_valid(native))
        assert.is_true(vim.api.nvim_win_is_valid(other))
        vim.w[agency].agency_bufnr = nil
        vim.w[native].agentic_bufnr = nil
        vim.api.nvim_win_close(agency, true)
        vim.api.nvim_win_close(native, true)
        vim.cmd.tabnext()
        vim.cmd.tabclose()
    end)
    describe("merge", function()
        it("merges two tables", function()
            local result = utils.merge({ a = 1, b = 2 }, { b = 3, c = 4 })
            assert.are.equal(1, result.a)
            assert.are.equal(3, result.b)
            assert.are.equal(4, result.c)
        end)

        it("second table wins on conflict", function()
            local result = utils.merge({ x = "old" }, { x = "new" })
            assert.are.equal("new", result.x)
        end)
    end)

    describe("is_executable", function()
        it("returns true for known executables", function()
            assert.is_true(utils.is_executable("ls"))
        end)

        it("returns false for nonexistent binaries", function()
            assert.is_false(utils.is_executable("__nonexistent_binary_xyz__"))
        end)
    end)

    describe("path_exists", function()
        it("returns truthy for existing path", function()
            assert.is_truthy(utils.path_exists(vim.fn.expand("~/.config/nvim/init.lua")))
        end)

        it("returns falsy for missing path", function()
            assert.is_falsy(utils.path_exists("/tmp/__does_not_exist_xyz__"))
        end)
    end)

    describe("is_fugitive_buffer", function()
        it("returns false for normal buffer", function()
            assert.is_false(utils.is_fugitive_buffer(0))
        end)
    end)
end)