#!/usr/bin/env bash
NVIM_ADDR="${NVIM_SOCKET_PATH:-$NVIM}"
[[ -z "$NVIM_ADDR" ]] && exit 0

win=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --window) win="$2"; shift 2 ;;
    *) file="$1"; shift ;;
  esac
done

[[ -z "$file" ]] && exit 1

if [[ -n "$win" ]]; then
  lua="(function() vim.api.nvim_set_current_win(${win}) vim.cmd('edit '..vim.fn.fnameescape(_A)) return 0 end)()"
else
  lua="(function() vim.cmd('edit '..vim.fn.fnameescape(_A)) return 0 end)()"
fi

file_escaped="${file//\\/\\\\}"
file_escaped="${file_escaped//\"/\\\"}"
lua_escaped="${lua//\\/\\\\}"
lua_escaped="${lua_escaped//\"/\\\"}"

nvim --server "$NVIM_ADDR" --remote-expr "luaeval(\"${lua_escaped}\", \"${file_escaped}\")"