#!/usr/bin/env bash
NVIM_ADDR="${NVIM_SOCKET_PATH:-$NVIM}"
[[ -z "$NVIM_ADDR" ]] && exit 0
[[ -z "$1" ]] && exit 1
lua="$1"
lua="${lua//\\/\\\\}"
lua="${lua//\"/\\\"}"
nvim --server "$NVIM_ADDR" --remote-expr "luaeval(\"(function() ${lua} end)()\")"